services:
  migrations:
    build:
      context: .
      dockerfile: ./docker/migrations.Dockerfile
    volumes:
      - ./db:/app/db
      - ./.env:/app/db/.env

  # Webapp service (frontend)
  webapp:
    build:
      context: .
      dockerfile: ./docker/webapp.Dockerfile
    depends_on:
      migrations:
        condition: service_completed_successfully
    network_mode: "host"
    ports:
      - "5000:5000"
    volumes:
      - ./webapp:/app/webapp

  # Matcher service
  matcher:
    build:
      context: .
      dockerfile: ./docker/matcher.Dockerfile
    depends_on:
      migrations:
        condition: service_completed_successfully
    network_mode: "host"
    volumes:
      - ./services/matcher:/app/services/matcher
      - ./.env:/app/services/matcher/.env
