--
-- PostgreSQL database dump
--

-- Dumped from database version 16.8
-- Dumped by pg_dump version 16.8 (Ubuntu 16.8-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: avnadmin
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO avnadmin;

--
-- Name: set_current_timestamp_updated_at(); Type: FUNCTION; Schema: public; Owner: avnadmin
--

CREATE FUNCTION public.set_current_timestamp_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
declare
  _new record;
begin
  _new := new;
  _new. "updated_at" = now();
  return _new;
end;
$$;


ALTER FUNCTION public.set_current_timestamp_updated_at() OWNER TO avnadmin;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts; Type: TABLE; Schema: public; Owner: avnadmin
--

CREATE TABLE public.accounts (
    email text,
    id integer NOT NULL,
    name text,
    smazano boolean DEFAULT false NOT NULL
);


ALTER TABLE public.accounts OWNER TO avnadmin;

--
-- Name: COLUMN accounts.smazano; Type: COMMENT; Schema: public; Owner: avnadmin
--

COMMENT ON COLUMN public.accounts.smazano IS 'deleted';


--
-- Name: campaign_dismissals; Type: TABLE; Schema: public; Owner: avnadmin
--

CREATE TABLE public.campaign_dismissals (
    campaign_id integer NOT NULL,
    account_id integer NOT NULL
);


ALTER TABLE public.campaign_dismissals OWNER TO avnadmin;

--
-- Name: campaign_notifications; Type: TABLE; Schema: public; Owner: avnadmin
--

CREATE TABLE public.campaign_notifications (
    campaign_id integer NOT NULL,
    id integer NOT NULL,
    content text NOT NULL,
    confirmed boolean DEFAULT false NOT NULL,
    read boolean DEFAULT false NOT NULL,
    account_id integer NOT NULL,
    ts timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.campaign_notifications OWNER TO avnadmin;

--
-- Name: campaign_notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: avnadmin
--

ALTER TABLE public.campaign_notifications ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.campaign_notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: campaigns; Type: TABLE; Schema: public; Owner: avnadmin
--

CREATE TABLE public.campaigns (
    maintainer_id integer,
    title text,
    description text,
    id integer NOT NULL,
    cause_id integer,
    suggested_highest_threshold bigint DEFAULT '8000000000'::bigint NOT NULL,
    suggested_lowest_threshold bigint DEFAULT '1'::bigint,
    suggested_optimal_threshold bigint DEFAULT '10'::bigint NOT NULL,
    smazano boolean DEFAULT false NOT NULL,
    stealth boolean DEFAULT false NOT NULL,
    uri text,
    twitter_tag text
);


ALTER TABLE public.campaigns OWNER TO avnadmin;

--
-- Name: campaigns_id_seq; Type: SEQUENCE; Schema: public; Owner: avnadmin
--

ALTER TABLE public.campaigns ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.campaigns_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: causes; Type: TABLE; Schema: public; Owner: avnadmin
--

CREATE TABLE public.causes (
    id integer NOT NULL,
    title text DEFAULT ''::text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    maintainer_id integer NOT NULL
);


ALTER TABLE public.causes OWNER TO avnadmin;

--
-- Name: causes_id_seq; Type: SEQUENCE; Schema: public; Owner: avnadmin
--

ALTER TABLE public.causes ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.causes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: participations; Type: TABLE; Schema: public; Owner: avnadmin
--

CREATE TABLE public.participations (
    id integer NOT NULL,
    account_id integer NOT NULL,
    campaign_id integer NOT NULL,
    threshold integer NOT NULL,
    condition_is_fulfilled boolean DEFAULT false NOT NULL,
    confirmed boolean DEFAULT false NOT NULL
);


ALTER TABLE public.participations OWNER TO avnadmin;

--
-- Name: participation_id_seq; Type: SEQUENCE; Schema: public; Owner: avnadmin
--

ALTER TABLE public.participations ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.participation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: avnadmin
--

CREATE TABLE public.users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    display_name text,
    avatar_url text
);


ALTER TABLE public.users OWNER TO avnadmin;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: avnadmin
--

ALTER TABLE public.accounts ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: verified_user_authentications; Type: TABLE; Schema: public; Owner: avnadmin
--

CREATE TABLE public.verified_user_authentications (
    account_id integer NOT NULL,
    provider text NOT NULL,
    login_name text NOT NULL
);


ALTER TABLE public.verified_user_authentications OWNER TO avnadmin;

--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: avnadmin
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- Name: campaign_dismissals campaign_dismissals_pkey; Type: CONSTRAINT; Schema: public; Owner: avnadmin
--

ALTER TABLE ONLY public.campaign_dismissals
    ADD CONSTRAINT campaign_dismissals_pkey PRIMARY KEY (campaign_id, account_id);


--
-- Name: campaign_notifications campaign_notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: avnadmin
--

ALTER TABLE ONLY public.campaign_notifications
    ADD CONSTRAINT campaign_notifications_pkey PRIMARY KEY (id);


--
-- Name: campaigns campaigns_pkey; Type: CONSTRAINT; Schema: public; Owner: avnadmin
--

ALTER TABLE ONLY public.campaigns
    ADD CONSTRAINT campaigns_pkey PRIMARY KEY (id);


--
-- Name: campaigns campaigns_uri_key; Type: CONSTRAINT; Schema: public; Owner: avnadmin
--

ALTER TABLE ONLY public.campaigns
    ADD CONSTRAINT campaigns_uri_key UNIQUE (uri);


--
-- Name: causes causes_id; Type: CONSTRAINT; Schema: public; Owner: avnadmin
--

ALTER TABLE ONLY public.causes
    ADD CONSTRAINT causes_id PRIMARY KEY (id);


--
-- Name: accounts id; Type: CONSTRAINT; Schema: public; Owner: avnadmin
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT id UNIQUE (id);


--
-- Name: participations participation_pkey; Type: CONSTRAINT; Schema: public; Owner: avnadmin
--

ALTER TABLE ONLY public.participations
    ADD CONSTRAINT participation_pkey PRIMARY KEY (id);


--
-- Name: participations participations_campaign_id_user_id; Type: CONSTRAINT; Schema: public; Owner: avnadmin
--

ALTER TABLE ONLY public.participations
    ADD CONSTRAINT participations_campaign_id_user_id UNIQUE (campaign_id, account_id);


--
-- Name: accounts users_name_key; Type: CONSTRAINT; Schema: public; Owner: avnadmin
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT users_name_key UNIQUE (name);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: avnadmin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users set_public_users_updated_at; Type: TRIGGER; Schema: public; Owner: avnadmin
--

CREATE TRIGGER set_public_users_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.set_current_timestamp_updated_at();


--
-- Name: campaign_dismissals campaign_dismissals_campaign_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: avnadmin
--

ALTER TABLE ONLY public.campaign_dismissals
    ADD CONSTRAINT campaign_dismissals_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: campaign_dismissals campaign_dismissals_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: avnadmin
--

ALTER TABLE ONLY public.campaign_dismissals
    ADD CONSTRAINT campaign_dismissals_user_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: campaign_notifications campaign_notifications_campaign_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: avnadmin
--

ALTER TABLE ONLY public.campaign_notifications
    ADD CONSTRAINT campaign_notifications_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: campaign_notifications campaign_notifications_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: avnadmin
--

ALTER TABLE ONLY public.campaign_notifications
    ADD CONSTRAINT campaign_notifications_user_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: campaigns campaigns_cause_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: avnadmin
--

ALTER TABLE ONLY public.campaigns
    ADD CONSTRAINT campaigns_cause_id_fkey FOREIGN KEY (cause_id) REFERENCES public.causes(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: campaigns campaigns_maintainer_fkey; Type: FK CONSTRAINT; Schema: public; Owner: avnadmin
--

ALTER TABLE ONLY public.campaigns
    ADD CONSTRAINT campaigns_maintainer_fkey FOREIGN KEY (maintainer_id) REFERENCES public.accounts(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: causes causes_maintainer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: avnadmin
--

ALTER TABLE ONLY public.causes
    ADD CONSTRAINT causes_maintainer_id_fkey FOREIGN KEY (maintainer_id) REFERENCES public.accounts(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: participations participation_campaign_fkey; Type: FK CONSTRAINT; Schema: public; Owner: avnadmin
--

ALTER TABLE ONLY public.participations
    ADD CONSTRAINT participation_campaign_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: participations participation_user_fkey; Type: FK CONSTRAINT; Schema: public; Owner: avnadmin
--

ALTER TABLE ONLY public.participations
    ADD CONSTRAINT participation_user_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: verified_user_authentications verified_user_authentications_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: avnadmin
--

ALTER TABLE ONLY public.verified_user_authentications
    ADD CONSTRAINT verified_user_authentications_user_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

